name: openssh
on: ["push", "workflow_dispatch"]
jobs:
  build_pkg:
    uses: gardenlinux/package-build/.github/workflows/build_pkg.yml@main
    with:
      build_options: nocheck parallel=8
      build_profiles: noudeb
